apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qh5qrp68q-nodejs
  janus-idp.io/tekton: qh5qrp68q-nodejs
  backstage.io/kubernetes-id: qh5qrp68q-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qh5qrp68q-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
